/*
 *--------------------------------------------------------------------------------------------------
 * DS-SLAM: A Semantic Visual SLAM towards Dynamic Environments
　*　Author(s):
 * Chao Yu, Zuxin Liu, Xinjun Liu, Fugui Xie, Yi Yang, Qi Wei, Fei Qiao qiaofei@mail.tsinghua.edu.cn
 * Created by Yu Chao@2018.12.03
 * --------------------------------------------------------------------------------------------------
 * DS-SLAM is a optimized SLAM system based on the famous ORB-SLAM2. If you haven't learn ORB_SLAM2 code, 
 * you'd better to be familiar with ORB_SLAM2 project first. Compared to ORB_SLAM2, 
 * we add anther two threads including semantic segmentation thread and densemap creation thread. 
 * You should pay attention to Frame.cc, ORBmatcher.cc, Pointcloudmapping.cc and Segment.cc.
 * 
 *　@article{murORB2,
 *　title={{ORB-SLAM2}: an Open-Source {SLAM} System for Monocular, Stereo and {RGB-D} Cameras},
　*　author={Mur-Artal, Ra\'ul and Tard\'os, Juan D.},
　* journal={IEEE Transactions on Robotics},
　*　volume={33},
　* number={5},
　* pages={1255--1262},
　* doi = {10.1109/TRO.2017.2705103},
　* year={2017}
 *　}
 * --------------------------------------------------------------------------------------------------
 * Copyright (C) 2018, iVip Lab @ EE, THU (https://ivip-tsinghua.github.io/iViP-Homepage/) and 
 * Advanced Mechanism and Roboticized Equipment Lab. All rights reserved.
 *
 * Licensed under the GPLv3 License;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * https://github.com/ivipsourcecode/DS-SLAM/blob/master/LICENSE
 *--------------------------------------------------------------------------------------------------
 */

#ifndef POINTCLOUDMAPPING_H
#define POINTCLOUDMAPPING_H

#include "System.h"
#include "Converter.h"
#include <condition_variable>

#include <pcl/common/transforms.h>
#include <pcl/point_types.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/filters/statistical_outlier_removal.h>
#include <pcl_ros/transforms.h>
#include <pcl_conversions/pcl_conversions.h>

using namespace ORB_SLAM3;

class PointCloudMapping
{

public:
    typedef pcl::PointXYZRGBA PointT;
    typedef pcl::PointCloud<PointT> PointCloud;

    /**
     * @brief Construct a new Point Cloud Mapping object
     * 
     * @param resolution_ 
     */
    PointCloudMapping(double resolution_);

    /**
     * @brief Insert new keyframe and RGB-D image, and trigger pointcloud generation process
     * 
     * @param kf keyframe 
     * @param color rgb image 
     * @param depth depth image
     * @param seqNum sequence number of this frame
     */
    void insertKeyFrame(KeyFrame *kf, cv::Mat &color, cv::Mat &depth, const int seqNum);

    /**
     * @brief Shuts down all threads properly
     */
    void shutdown();

protected:
    PointCloud::Ptr generatePointCloud(KeyFrame *kf, cv::Mat color, cv::Mat depth, int seqNum);

    boost::shared_ptr<thread> viewerThread;
    boost::shared_ptr<thread> pclThread;

    bool shutDownFlag = false;
    std::mutex shutDownMutex;
    std::mutex keyFrameUpdateMutex;
    std::condition_variable keyFrameUpdated;
    std::condition_variable newMaskArrived;

    // Data to generate point clouds
    std::map<int, cv::Mat> maskMap;
    std::vector<KeyFrame *> keyframes;
    std::vector<cv::Mat> colorImgs;
    std::vector<cv::Mat> depthImgs;
    std::vector<int> imgMasksSeq;
    std::mutex keyframeMutex;
    std::mutex maskMutex;
    uint16_t lastKeyframeSize = 0;

    double resolution = 0.005;
    pcl::VoxelGrid<PointT> voxel;
    pcl::StatisticalOutlierRemoval<PointT> sor;

    /**
     * @brief Runs all functionalities in a new thread
     */
    void viewer();

    /**
     * @brief Callback triggered when a new mask is received from ROS Node 
     * 
     * @param msgMask ROS message image including the mask 
     */
    void imageMaskCallback(const sensor_msgs::ImageConstPtr &msgMask);

    /**
     * @brief Generates and publishes the pointcloud in a separate thread
     * 
     * @param N Total number of all (keyframes, RGB-D images) inserted
     */
    void generateAndPublishPointCloud(size_t N);

    /**
     * @brief Calculates transformation matrix based on camera pose
     * and publishes it as a ROS tf message to transfrom the pointcloud to world coordinates
     * 
     * @param cameraPose camera pose generated by ORB-SLAM3
     */
    void broadcastTranformMat(Eigen::Isometry3d cameraPose);
};

#endif // POINTCLOUDMAPPING_H
